AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  SuggestExtensions: false
  Exclude:
    - vendor/**/*
    - bin/**/*

require:
  - rubocop-performance
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

Style/Documentation:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

RSpec/Capybara/FeatureMethods:
  Enabled: false
