language: ruby

sudo: false

rvm:
  - 2.3.0
  - 2.2
  - 2.1
  - 2.0.0
  - rbx-2
  - jruby-19mode
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2

gemfile:
  - gemfiles/rails_3_2.gemfile
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5.gemfile
  - gemfiles/rack_1.5.2.gemfile
