---
name: edge
on:
  pull_request:
    branches:
      - "*"
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 2.7
            gemfile: 'gemfiles/rails_edge.gemfile'
          - ruby: 2.7
            gemfile: 'gemfiles/rack_edge.gemfile'
          - ruby: "ruby-head"
          - ruby: "truffleruby-head"
          - ruby: "jruby-head"
    runs-on: ubuntu-20.04
    continue-on-error: true
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run tests
      run: bundle exec rake spec
